url: https://nirhalfon.com
baseurl: https://nirhalfon.com/

# Site settings
title: Nir Halfon - CyberSecurity Consulting
email: consult@nirhalfon.com
description: "Nir Halfon CyberSecurity Consulting | Digital Forensics | Incident Response | Security Analyst | Threat Hunting | SOC Managment | Training"


# Team names, titles and social links
people:
- name: Nir Halfon
  pic: 1
  position: Mastering the Digital Forensics Incident Response
  social:
    - title: twitter
      url: https://twitter.com/nirhalfon1
    - title: facebook
      url: https://www.facebook.com/nir.halfon
    - title: linkedin
      url: https://www.linkedin.com/in/nirhalfon

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/nirhalfon1
  - title: facebook
    url: https://www.facebook.com/nir.halfon
  - title: facebook
    url: https://www.facebook.com/nir.halfon


# Postal address (add as many lines as necessary)
address:
  - line: Beer Sheva
  - line: Israel

# Build settings
markdown: kramdown
permalink: pretty